window.onload = function(){
  var request = new XMLHttpRequest();
  request.open("GET", "grafika/arabica_pojedyncze240px.png");
  request.send("");
  request = new XMLHttpRequest();
  request.open("GET", "grafika/arabica-excelso_pojedyncze240px.png");
  request.send("");
  request = new XMLHttpRequest();
  request.open("GET", "grafika/robusta_pojedyncze240px.png");
  request.send("");
  request = new XMLHttpRequest();
  request.open("GET", "grafika/arabica_mielona3240px.png");
  request.send("");
  request = new XMLHttpRequest();
  request.open("GET", "grafika/arabica-excelso_mielona3240px.png");
  request.send("");
  request = new XMLHttpRequest();
  request.open("GET", "grafika/robusta_mielona3240px.png");
  request.send("");
  request = new XMLHttpRequest();
  request.open("GET", "grafika/flat-white_filiz240px.png");
  request.send("");
  request = new XMLHttpRequest();
  request.open("GET", "grafika/cortado_filiz240px.png");
  request.send("");
  request = new XMLHttpRequest();
  request.open("GET", "grafika/capuccino_filiz240px.png");
  request.send("");
  request = new XMLHttpRequest();
  request.open("GET", "grafika/latte-macchiato_filiz240px.png");
  request.send("");
}